version: '3'

services:

  auth_server:
    container_name: auth_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    networks:
      - backend

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'rootroot'
      POSTGRES_DB: 'auth'
    ports:
      - "5432:5432"
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend: